### ISSUE TITLE
Support binary builds

### ISSUE THREAD

**Issue by gnunn1** [jw3/sbt-s2i#2]
Not a showstopper or anything, but it would be nice if this could support binary builds at some point.

**Comment by jw3** [comment]
Can you clarify what you mean by binary build?

**Comment by gnunn1** [comment]
A binary build is where you upload the already built binary artifact, i.e jar, instead of source code to s2i. There is a description of it here:

https://docs.openshift.com/container-platform/3.6/dev_guide/dev_tutorials/binary_builds.html

Having said that I think this can be closed, red hat has a jdk s2i image now in openshift and you can just use that for binary builds.
